/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";import QRCode from "qrcode";import { useCallback,useEffect,useState } from "react";
type Slide={kicker:string;title:string;accent?:string;body?:string;type?:"cover"|"cards"|"journey"|"flow"|"qr";items?:string[]};
const slides:Slide[]=[
 {type:"cover",kicker:"SPMB SMK NURUL IMAN",title:"Lanjutkan perjalanan.",accent:"Siapkan masa depan.",body:"Adab terjaga · Skill bertumbuh · Masa depan dipersiapkan"},
 {kicker:"SEBENTAR LAGI LULUS",title:"Sesudah SMP,",accent:"anak akan ke mana?",body:"Pertanyaan ini bukan hanya tentang sekolah berikutnya. Ini tentang lingkungan, kemampuan, dan pilihan hidup yang sedang dibangun."},
 {type:"cards",kicker:"YANG DIPIKIRKAN WALI",title:"Empat hal.",accent:"Satu keputusan besar.",items:["Agama tetap terjaga","Pergaulan didampingi","Keterampilan bertumbuh","Masa depan dipersiapkan"]},
 {kicker:"JANGAN PUTUS PONDASI",title:"Yang sudah baik,",accent:"jangan berhenti.",body:"Pembiasaan ibadah, adab, Al-Qur’an, dan lingkungan pesantren tetap menjadi akar saat siswa belajar teknologi dan kreativitas."},
 {type:"cards",kicker:"PONDASI PENDIDIKAN",title:"Tiga pilar.",accent:"Tumbuh bersama.",items:["Adab & Agama","Skill & Teknologi","Masa Depan"]},
 {type:"journey",kicker:"PERJALANAN 3 TAHUN",title:"Bertumbuh",accent:"bertahap.",items:["X · Fondasi Kreatif","XI · Naik Level","XII · Dunia Nyata"]},
 {type:"flow",kicker:"CARA BELAJAR",title:"Tidak berhenti",accent:"di teori.",items:["LEARN","PRACTICE","PROJECT","PORTFOLIO"]},
 {kicker:"SHOWCASE",title:"Karya adalah",accent:"jejak proses.",body:"Desain, foto, video, film, coding, branding, dan proyek membuat perkembangan siswa bisa dilihat dan didiskusikan."},
 {type:"cards",kicker:"HASIL 3 TAHUN",title:"Bukan satu janji.",accent:"Banyak bekal.",items:["Portofolio terkurasi","Pengalaman PKL","Uji kompetensi","Kebiasaan menyelesaikan proyek"]},
 {kicker:"BISA KULIAH?",title:"Tentu, pilihan",accent:"tetap terbuka.",body:"Siswa dibekali untuk mempertimbangkan pendidikan lanjutan, bekerja, berkarya, atau memulai usaha—sesuai kesiapan dan tujuan masing-masing."},
 {kicker:"KEUNGGULAN SISWA INTERNAL",title:"Tidak mulai",accent:"dari nol.",body:"Siswa yang sudah tumbuh di lingkungan Nurul Iman membawa pondasi adab, kebiasaan, dan relasi yang dapat dilanjutkan ke tahap berikutnya."},
 {kicker:"SETIAP ANAK BERBEDA",title:"Mulai dari",accent:"mengenal minat.",body:"Pemetaan minat awal membantu siswa dan wali membuka percakapan tentang bidang yang membuat anak antusias untuk belajar."},
 {type:"cards",kicker:"PERTANYAAN YANG WAJAR",title:"Boleh tanya",accent:"apa saja.",items:["Belum bisa desain?","Takut tidak betah?","Bagaimana PKL?","Apakah bisa kuliah?"]},
 {kicker:"BIAYA PENDIDIKAN",title:"Jelas sejak awal.",accent:"Direncanakan bersama.",body:"Rincian resmi ditampilkan setelah ditetapkan sekolah. Tidak ada nominal rekaan atau janji keringanan yang belum disahkan."},
 {type:"flow",kicker:"ALUR KONSULTASI",title:"Mulai dengan",accent:"percakapan.",items:["CERITAKAN","PAHAMI","KUNJUNGI","PUTUSKAN"]},
 {type:"cards",kicker:"STUDENT EXPERIENCE",title:"Anak ikut",accent:"menemukan jawabannya.",items:["Pemetaan minat","Jelajahi program","Lihat karya","Diskusi bersama wali"]},
 {kicker:"NI FUTURE",title:"Mondoknya tetap.",accent:"Skill-nya naik level.",body:"Melanjutkan perjalanan bukan berarti mengulang. Ini waktunya memperluas kemampuan, sambil tetap menjaga nilai yang sudah tumbuh."},
 {type:"qr",kicker:"MULAI DARI SINI",title:"Scan. Kenali.",accent:"Diskusikan bersama.",body:"Arahkan kamera ponsel ke QR untuk membuka pengalaman wali dan siswa."},
];
export default function Presentation(){const [index,setIndex]=useState(0),[qr,setQr]=useState("");const prev=useCallback(()=>setIndex(i=>Math.max(0,i-1)),[]),next=useCallback(()=>setIndex(i=>Math.min(slides.length-1,i+1)),[]);useEffect(()=>{QRCode.toDataURL(`${location.origin}/mulai`,{width:360,margin:2,color:{dark:"#0a1f2d",light:"#fffdf7"}}).then(setQr);const key=(e:KeyboardEvent)=>{if(e.key==="ArrowRight"||e.key===" ")next();if(e.key==="ArrowLeft")prev()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[next,prev]);const s=slides[index];async function fullscreen(){if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}return <main className="presentation"><div className="present-top"><Link href="/" className="present-brand">NI <span>FUTURE</span></Link><span>SPMB SMK NURUL IMAN · 2027/2028</span><button onClick={fullscreen}>⛶ Fullscreen</button></div><section className={`slide slide-${s.type??"text"}`}><div className="slide-number">{String(index+1).padStart(2,"0")}</div><div className="slide-copy"><div className="section-kicker light">{s.kicker}</div><h1>{s.title}<br/><em>{s.accent}</em></h1>{s.body&&<p>{s.body}</p>}{s.items&&<div className="slide-items">{s.items.map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div>}{s.type==="qr"&&<div className="qr-wrap">{qr&&<img src={qr} alt="QR menuju halaman Mulai"/>}<div><b>Buka di ponsel</b><span>/mulai</span></div></div>}</div><div className="slide-motif"><i/><i/><i/></div></section><div className="present-bottom"><div className="slide-progress"><i style={{width:`${(index+1)/slides.length*100}%`}}/></div><button onClick={prev} disabled={index===0}>← Sebelumnya</button><span>{index+1} / {slides.length}</span><button onClick={next} disabled={index===slides.length-1}>Berikutnya →</button></div></main>}
