import { NextResponse } from "next/server";
import { getDb } from "../../../db/firebase";
import { AssessmentPayloadError,scoreCanonicalAssessment } from "../../../lib/assessment-config";
import { consumeRateLimit } from "../../../lib/rate-limit";
import { createResultToken,verifyResultToken } from "../../../lib/result-token";
import { profileSchema,validationMessage } from "../../../lib/validation";
function limited(retryAfterSeconds:number){return NextResponse.json({error:"Terlalu banyak permintaan. Silakan coba kembali nanti."},{status:429,headers:{"Retry-After":String(retryAfterSeconds)}})}
export async function POST(request:Request){try{const ipLimit=await consumeRateLimit({request,scope:"interest-ip",limit:20,windowSeconds:3600});if(!ipLimit.allowed)return limited(ipLimit.retryAfterSeconds);const body=await request.json();if(!body||typeof body!=="object"||Array.isArray(body)||Object.keys(body).some(key=>key!=="profile"&&key!=="answers"))return NextResponse.json({error:"Data pemetaan tidak valid."},{status:400});const profile=profileSchema.safeParse(body.profile);if(!profile.success)return NextResponse.json({error:validationMessage(profile.error)},{status:400});let scored;try{scored=scoreCanonicalAssessment(body.answers)}catch(error){if(error instanceof AssessmentPayloadError)return NextResponse.json({error:error.message},{status:400});throw error}const {studentName,parentName,school,phone}=profile.data,{scores,top,second,answers}=scored;const identityLimit=await consumeRateLimit({request,scope:"interest-identity",identifier:phone,limit:8,windowSeconds:86400});if(!identityLimit.allowed)return limited(identityLimit.retryAfterSeconds);const db=getDb(),leadRef=db.collection("leads").doc(),sessionRef=db.collection("interestSessions").doc(),now=new Date().toISOString();const batch=db.batch();batch.set(leadRef,{studentName,parentName,phone,school,source:"INTEREST_MAPPING",topCategory:top,secondCategory:second,status:"INTERESTED",createdAt:now,updatedAt:now});batch.set(sessionRef,{leadId:leadRef.id,rawAnswers:answers.map(answer=>answer.answerId),categoryScores:scores,topCategory:top,secondCategory:second,studentName,completedAt:now});await batch.commit();return NextResponse.json({id:sessionRef.id,token:createResultToken(sessionRef.id),studentName,scores,top,second},{status:201})}catch{return NextResponse.json({error:"Hasil belum dapat disimpan."},{status:500})}}
export async function GET(request:Request){try{const url=new URL(request.url),id=url.searchParams.get("id")??"",token=url.searchParams.get("token")??"";if(!id||!token||!verifyResultToken(token,id))return NextResponse.json({error:"Akses hasil tidak valid atau sudah kedaluwarsa."},{status:403});const snap=await getDb().collection("interestSessions").doc(id).get();if(!snap.exists)return NextResponse.json({error:"Tidak ditemukan"},{status:404});const d=snap.data()!;return NextResponse.json({id:snap.id,studentName:d.studentName, scores:d.categoryScores,top:d.topCategory,second:d.secondCategory})}catch{return NextResponse.json({error:"Belum dapat dimuat"},{status:500})}}
