"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import { SiteHeader } from "../ui";
import { Choice,questions } from "./questions";

type Profile={studentName:string;school:string;parentName:string;phone:string};
export default function InterestPage(){const router=useRouter();const [stage,setStage]=useState<"intro"|"quiz"|"saving">("intro"),[profile,setProfile]=useState<Profile>({studentName:"",school:"",parentName:"",phone:""}),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Choice[]>([]),[error,setError]=useState("");
 function start(e:FormEvent<HTMLFormElement>){e.preventDefault();setStage("quiz")}
 async function choose(choice:Choice){const next=[...answers,choice];setAnswers(next);if(index<questions.length-1){setIndex(index+1);return}setStage("saving");const res=await fetch("/api/interest",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({profile,answers:next})});if(!res.ok){setError((await res.json()).error??"Belum berhasil menyimpan hasil.");setStage("quiz");return}const result=await res.json();sessionStorage.setItem(`ni-result-${result.id}`,JSON.stringify(result));router.push(`/minat/hasil/${result.id}`)}
 function back(){if(index===0){setStage("intro");setAnswers([])}else{setIndex(index-1);setAnswers(answers.slice(0,-1))}}
 const q=questions[index];return <main className="mapping-page"><SiteHeader/>{stage==="intro"?<section className="mapping-intro"><div className="mapping-copy"><div className="section-kicker light">PEMETAAN MINAT · ± 5 MENIT</div><h1>Temukan<br/><em>Potensimu.</em></h1><p>Kenali hal-hal yang membuatmu tertarik, lalu lihat bagaimana minat itu bisa dikembangkan selama tiga tahun di SMK.</p><div className="disclaimer"><b>Perlu diketahui</b><span>Pemetaan ini membantu mengenali minat awal siswa dan bukan tes psikologi atau diagnosis kemampuan.</span></div></div><div className="profile-card"><div className="card-step">LANGKAH 01 / 02</div><h2>Sebelum mulai,<br/>boleh kenalan?</h2><form className="stack-form" onSubmit={start}><label>Nama siswa<input required value={profile.studentName} onChange={e=>setProfile({...profile,studentName:e.target.value})} placeholder="Nama lengkap"/></label><label>Asal sekolah<input required value={profile.school} onChange={e=>setProfile({...profile,school:e.target.value})} placeholder="Nama sekolah asal"/></label><div className="form-row"><label>Nama wali<input required value={profile.parentName} onChange={e=>setProfile({...profile,parentName:e.target.value})} placeholder="Nama wali"/></label><label>WhatsApp wali<input required inputMode="tel" pattern="(?:\+62|62|0)8[1-9][0-9\s-]{6,14}" value={profile.phone} onChange={e=>setProfile({...profile,phone:e.target.value})} placeholder="08xxxxxxxxxx"/></label></div><button className="button primary full">Mulai Pemetaan <span>→</span></button><small>Data dijaga dan hanya digunakan untuk pendampingan SPMB.</small></form></div></section>:stage==="saving"?<div className="saving-screen"><span className="loader"/><h2>Menyusun hasilmu…</h2><p>Kami menghitung setiap jawaban secara konsisten.</p></div>:<section className="quiz-shell"><div className="quiz-top"><button onClick={back}>← Kembali</button><div><span>{String(index+1).padStart(2,"0")}</span> / {questions.length}</div></div><div className="progress"><i style={{width:`${(index+1)/questions.length*100}%`}}/></div><div className="quiz-content"><div className="section-kicker light">PILIH YANG PALING MENGGAMBARKANMU</div><h2>{q.prompt}</h2>{error&&<p className="quiz-error">{error}</p>}<div className="choice-grid">{q.choices.map(choice=><button key={choice.id} onClick={()=>choose(choice)}><span className="choice-symbol">{choice.symbol}</span><span><b>{choice.label}</b><small>{choice.hint}</small></span><i>↗</i></button>)}</div></div></section>}</main>}
