export type Choice={id:string;label:string;hint:string;symbol:string;weights:Record<string,number>};
export type Question={id:string;prompt:string;choices:Choice[]};
const c=(id:string,label:string,hint:string,symbol:string,weights:Record<string,number>):Choice=>({id,label,hint,symbol,weights});
export const questions:Question[]=[
 {id:"q1",prompt:"Saat punya waktu luang, saya lebih menikmati…",choices:[c("design","Membuat desain","Warna, bentuk, dan layout","◈",{creative:3,photo:1}),c("video","Mengedit video","Menyusun cerita bergerak","▶",{video:3,creative:1}),c("computer","Mengutak-atik komputer","Mencari tahu cara kerja teknologi","⌘",{technology:3,coding:2})]},
 {id:"q2",prompt:"Dalam sebuah kelompok, saya paling ingin bertugas…",choices:[c("visual","Membuat tampilan","Poster dan identitas visual","✦",{creative:3}),c("document","Mendokumentasikan","Mengambil foto dan video","◎",{photo:3,video:2}),c("organize","Mengatur strategi","Membagi peran dan target","↗",{business:3})]},
 {id:"q3",prompt:"Hasil karya yang paling membuat saya bangga adalah…",choices:[c("poster","Poster yang menarik","Pesannya mudah dipahami","▤",{creative:3}),c("film","Video bercerita","Ada alur dan suasana","▷",{video:3}),c("app","Program yang berjalan","Solusi digital sederhana","{ }",{coding:3,technology:2})]},
 {id:"q4",prompt:"Saya lebih cepat belajar ketika…",choices:[c("see","Melihat contoh","Membaca bentuk dan komposisi","◐",{creative:2,photo:2}),c("practice","Langsung praktik","Mencoba alat dan memperbaiki","⚙",{technology:3,coding:1}),c("discuss","Berdiskusi","Mengembangkan ide bersama","↔",{business:2,video:1})]},
 {id:"q5",prompt:"Hal yang paling ingin saya pelajari lebih jauh…",choices:[c("camera","Kamera & cahaya","Mengabadikan momen dengan tepat","◉",{photo:3,video:1}),c("code","Coding","Membangun sesuatu dari logika","</>",{coding:3,technology:2}),c("sell","Bisnis kreatif","Membawa karya bertemu pembeli","¤",{business:3,creative:1})]},
 {id:"q6",prompt:"Jika diberi satu proyek sekolah, saya memilih…",choices:[c("brand","Membuat brand","Logo, warna, dan kemasan","B",{creative:3,business:2}),c("shortfilm","Membuat film pendek","Konsep, rekam, dan edit","▻",{video:3,photo:2}),c("website","Membuat website","Tampilan dan fungsi","W",{coding:3,technology:2,creative:1})]},
 {id:"q7",prompt:"Tantangan yang terasa paling seru…",choices:[c("compose","Mengatur komposisi","Membuat visual terasa pas","▦",{creative:3,photo:2}),c("debug","Mencari kesalahan","Menemukan penyebab dan solusi","!",{coding:3,technology:2}),c("pitch","Meyakinkan orang","Menjelaskan nilai sebuah ide","↑",{business:3})]},
 {id:"q8",prompt:"Saat melihat konten digital, saya sering memperhatikan…",choices:[c("look","Tampilan visual","Tipografi dan warna","Aa",{creative:3}),c("story","Cara bercerita","Transisi, ritme, dan suara","≈",{video:3}),c("shot","Sudut pengambilan","Cahaya dan momen","⌾",{photo:3})]},
 {id:"q9",prompt:"Saya ingin karya saya nantinya…",choices:[c("useful","Memudahkan orang","Bekerja sebagai solusi","+",{technology:3,coding:2}),c("memorable","Diingat orang","Punya cerita dan rasa","✧",{video:2,photo:2,creative:1}),c("valuable","Punya nilai jual","Dapat dikembangkan jadi usaha","Rp",{business:3})]},
 {id:"q10",prompt:"Lingkungan belajar yang paling membuat saya berkembang…",choices:[c("studio","Studio kreatif","Banyak eksplorasi visual","□",{creative:2,photo:2,video:2}),c("lab","Lab teknologi","Banyak eksperimen dan logika","#",{technology:3,coding:3}),c("market","Proyek nyata","Ada pengguna dan tujuan bisnis","↗",{business:3,technology:1})]},
];
export const categoryNames:Record<string,string>={creative:"Creative Visual",video:"Video Creator",photo:"Photography",technology:"Technology",coding:"Coding",business:"Entrepreneurship"};
